// <auto-generated />
using Metadados.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Metadados.Migrations
{
    [DbContext(typeof(MetadadosContext))]
    partial class MetadadosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Metadados.Models.Localizacao_tipo", b =>
                {
                    b.Property<int>("sky_localizacao_tipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sky_localizacao_tipo"), 1L, 1);

                    b.Property<string>("nom_localizacao_tipo")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("sky_localizacao_tipo");

                    b.ToTable("Localizacao_tipo");
                });

            modelBuilder.Entity("Metadados.Models.Mapeamento", b =>
                {
                    b.Property<int>("sky_mapeamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sky_mapeamento"), 1L, 1);

                    b.Property<string>("dsc_mapeamento_colunas")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int>("sky_objeto_destino")
                        .HasColumnType("int");

                    b.Property<int>("sky_objeto_origem")
                        .HasColumnType("int");

                    b.Property<int>("sky_pipeline")
                        .HasColumnType("int");

                    b.HasKey("sky_mapeamento");

                    b.ToTable("Mapeamento");
                });

            modelBuilder.Entity("Metadados.Models.Objeto", b =>
                {
                    b.Property<int>("sky_objeto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sky_objeto"), 1L, 1);

                    b.Property<string>("dsc_coluna_ranges")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("nom_compactacao")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("nom_entidade")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("nom_objeto")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("nom_tabela")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int>("sky_objeto_configuracao")
                        .HasColumnType("int");

                    b.Property<int>("sky_objeto_localizacao")
                        .HasColumnType("int");

                    b.HasKey("sky_objeto");

                    b.ToTable("Objeto");
                });

            modelBuilder.Entity("Metadados.Models.Objeto_configuracao", b =>
                {
                    b.Property<int>("sky_objeto_configuracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sky_objeto_configuracao"), 1L, 1);

                    b.Property<string>("dsc_delimitador_coluna")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("dsc_delimitador_detalhe")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("dsc_encode")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("dsc_qualificador_texto")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("num_pular_linha")
                        .HasColumnType("int");

                    b.Property<int>("sky_objeto_tipo")
                        .HasColumnType("int");

                    b.HasKey("sky_objeto_configuracao");

                    b.ToTable("Objeto_configuracao");
                });

            modelBuilder.Entity("Metadados.Models.Objeto_localizacao", b =>
                {
                    b.Property<int>("sky_objeto_localizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sky_objeto_localizacao"), 1L, 1);

                    b.Property<string>("dsc_endereco_localizacao")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("nom_fornecedor")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("nom_objeto_identificador")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("nom_password")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("nom_usuario")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<int>("num_porta")
                        .HasColumnType("int");

                    b.Property<int>("sky_localizacao_tipo")
                        .HasColumnType("int");

                    b.HasKey("sky_objeto_localizacao");

                    b.ToTable("Objeto_localizacao");
                });

            modelBuilder.Entity("Metadados.Models.Objeto_tipo", b =>
                {
                    b.Property<int>("sky_objeto_tipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sky_objeto_tipo"), 1L, 1);

                    b.Property<string>("nom_objeto_tipo")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("sky_objeto_tipo");

                    b.ToTable("Objeto_tipo");
                });

            modelBuilder.Entity("Metadados.Models.Pipeline", b =>
                {
                    b.Property<int>("sky_pipeline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sky_pipeline"), 1L, 1);

                    b.Property<string>("nom_pipeline")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.HasKey("sky_pipeline");

                    b.ToTable("Pipeline");
                });
#pragma warning restore 612, 618
        }
    }
}
